### ISSUE TITLE
I found a subtle bug in CANN tutorial

### ISSUE THREAD

**Issue by ztqakita** [PKU-NIP-Lab/BrainPyExamples#1]
Hi! I found a bug in CANN tutorial that module `bp` is miswritten as `op` both in `.py` (line 75) and `.ipynb` (line 64) files. i.e.
```python
self.integral = op.odeint(self.derivative)
```
should be
```python
self.integral = bp.odeint(self.derivative)
```

**Comment by chaoming0625** [comment]
Dear @ztqakita , we have fixed this bug. The new version of CANN example please see https://brainpy-examples.readthedocs.io/en/latest/cann/Wu_2008_CANN.html

Thanks for your report!
