### ISSUE TITLE
Errors in Import brainpy

### ISSUE THREAD

**Issue by kezard** [PKU-NIP-Lab/BrainPyExamples#2]
I can pip the packages brainpy, braipylib, jax, jaxlib successfully according to the documentation guide, but when I import brainpy in my script the error occurs: "**AttributeError: module 'jax' has no attribute 'version'** ", I have no idea why this appears, and found no solutions. Any help is appreciated. Thank you.

**Comment by chaoming0625** [comment]
Are you using Apple M1?

**Comment by kezard** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by kezard** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
